// Generated by CoffeeScript 2.4.1
(function() {
  var canvas, ctxt;

  canvas = document.getElementById('env_view');

  ctxt = canvas.getContext('2d');

  window.addEventListener('resize', function(event) {
    ctxt.canvas.width = window.innerWidth - 300;
    ctxt.canvas.height = window.innerHeight;
    ctxt.fillStyle = 'green';
    return ctxt.fillRect(10, 10, 150, 100);
  });

  ctxt.canvas.width = window.innerWidth - 300;

  ctxt.canvas.height = window.innerHeight;

  ctxt.fillStyle = 'green';

  ctxt.fillRect(10, 10, 150, 100);

}).call(this);
